# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  pull_request:
    branches: 
      - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    services:
      wiremock:
        image: wiremock/wiremock
        ports: 
          - 8080:8080
        options: --verbose

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
      - name: Hello world
        run: echo "Hello World"
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: curl http://localhost:8080/__admin
