# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  pull_request:
    branches: 
      - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    services:
      wiremock:
        image: wiremock/wiremock
        ports: 
          - 8080:8080
          
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
      - name: Hello world
        run: echo "Hello World"
      - name: setup mock
        run: curl --data-binary "hello.json" http://localhost:8080/__admin/mapping
      - name: pogin 2
        run: curl -X POST --data '{ "request": { "url": "/get/this", "method": "GET" }, "response": { "status": 200, "body": "Here it is!\n" }}' http://localhost:8080/__admin/mappings/new
        
      # Runs a set of commands using the runners shell
      - name: Get config
        run: curl http://localhost:8080/__admin/mappings
      - name: Get hello
        run: curl -i http://localhost:8080/get/this
